Rename "Algorithms" to "Hash Functions" Registry
w3c-ccg/multihash pull request #6
Opened 2019-04-05 19:52 UTC by nichtich

The "Algorithms" listed in the registry are referenced as "Hash
Functions" so the terminology should be consistent.

2019-04-05 20:21 UTC, msporny requested changes

2019-04-05 20:21 UTC, msporny commented on gen-hash-functions-registry
> +# Script to generate the multihash hash functions registry from the CSV file
Hmm, so I agree that this should change... but "algorithms" nor "hash functions" are really the right thing. This is really a table of "identifiers that contain parameters to hash functions". How about this instead?

"Multihash Identifier Registry"

2019-04-05 20:21 UTC, msporny commented on gen-hash-functions-registry
> +# Script to generate the multihash hash functions registry from the CSV file
If you agree, please change the rest of this PR from "multihash hash functions" to "multihash identifier registry".

2019-04-05 20:22 UTC, msporny commented
Also, please rebase, seems like there are merge conflicts w/ this PR.

2019-04-05 21:28 UTC, nichtich commented
Sorry, the review system confuses me. Should I better commit on top of a PR instead of push --force and you squash the commits into one when doing a merge?

2019-04-06 17:24 UTC, merged

2019-04-06 17:24 UTC, msporny commented
> Sorry, the review system confuses me.

Looks like you figured it out. Thanks for the PR! :)